name: API CI

on:
  push:
    branches:
      - master
      - refactor
  pull_request:
    branches:
      - master
      - refactor

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install golangci-lint
      run: |
        go get github.com/golangci/golangci-lint/cmd/golangci-lint

    - name: Run linters
      working-directory: ./api
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin   
        ./pre-commit
 
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Calc coverage 
      working-directory: ./api
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin   
        go test ./... -v -covermode=count -coverprofile=coverage.out

    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.0
      with:
          infile: coverage.out
          outfile: coverage.lcov

    - name: Coveralls
      uses: coverallsapp/github-action@v1.0.1
      with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
          path-to-lcov: coverage.lcov


  test:
    runs-on: ubuntu-latest
    services:
      etcd:
        image: bitnami/etcd:3.4.13
        ports:
          - 2379:2379
          - 2380:2380
        env:
          ALLOW_NONE_AUTHENTICATION: yes

    steps:
    - uses: actions/checkout@v2
    - name: run Makefile
      run: |
        make license-check

    - name: get lua lib
      run: |
        wget https://github.com/api7/dag-to-lua/archive/v1.1.tar.gz
        sudo mkdir -p /go/api7-manager-api/dag-to-lua/
        tar -zxvf v1.1.tar.gz
        sudo mv ./dag-to-lua-1.1/lib/* /go/api7-manager-api/dag-to-lua/

    - name: install runtime
      run: |
        sudo apt-get update
        sudo apt-get install lua5.1
        sudo add-apt-repository ppa:longsleep/golang-backports
        sudo apt update
        export GO111MOUDULE=on
        sudo apt install golang-1.14-go

    - name: run test
      working-directory: ./api
      run: |
        export APIX_ETCD_ENDPOINTS=127.0.0.1:2379
        go test ./...
