name: API CI

on:
  push:
    branches:
      - master
      - refactor
  pull_request:
    branches:
      - master
      - refactor

jobs: 
  coverage:
    runs-on: ubuntu-latest
    services:
      etcd:
        image: bitnami/etcd:3.4.13
        ports:
          - 2379:2379
          - 2380:2380
        env:
          ALLOW_NONE_AUTHENTICATION: yes

    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.14'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      working-directory: ./api
      run: |
        go mod download

    - name: Run Unit tests
      working-directory: ./api
      run: |
        go test -race -covermode atomic -coverprofile=covprofile ./...

    - name: Install goveralls
      env:
        GO111MODULE: off
      run: go get github.com/mattn/goveralls

    - name: Send coverage
      working-directory: ./api
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: goveralls -coverprofile=covprofile -service=github


  test:
    runs-on: ubuntu-latest
    services:
      etcd:
        image: bitnami/etcd:3.4.13
        ports:
          - 2379:2379
          - 2380:2380
        env:
          ALLOW_NONE_AUTHENTICATION: yes

    steps:
    - uses: actions/checkout@v2
    - name: run Makefile
      run: |
        make license-check

    - name: get lua lib
      run: |
        wget https://github.com/api7/dag-to-lua/archive/v1.1.tar.gz
        sudo mkdir -p /go/api7-manager-api/dag-to-lua/
        tar -zxvf v1.1.tar.gz
        sudo mv ./dag-to-lua-1.1/lib/* /go/api7-manager-api/dag-to-lua/

    - name: install runtime
      run: |
        sudo apt-get update
        sudo apt-get install lua5.1
        sudo add-apt-repository ppa:longsleep/golang-backports
        sudo apt update
        export GO111MOUDULE=on
        sudo apt install golang-1.14-go

    - name: run test
      working-directory: ./api
      run: |
        export APIX_ETCD_ENDPOINTS=127.0.0.1:2379
        go test ./...
